### ISSUE TITLE
Publish latest changes to Cocoapods

### ISSUE THREAD

**Issue by JoeSzymanski** [mcudich/HeckelDiff#23]
We are currently making use of a fork of this repo because we need iOS 8 as the minimum supported version. It looks like you've fixed that here, but haven't pushed either 0.2.2 or the other changes after hat to the Cocoapods repo. Can there be a new version and can all of these versions get pushed into Cocoapods for public use?

**Comment by n3trino** [comment]
@mcudich i think you should fix the git tags and this will be sorted out.

**Comment by JoeSzymanski** [comment]
It looks like the release was done here but not published to Cocoapods.

**Comment by JoeSzymanski** [comment]
Bump on this. Version 0.2.2 and 0.2.3 appear to be properly tagged, but they are not available in the CocoaPods spec repo at all.

**Comment by absolute-heike** [comment]
👍 Yeah, I also have issues with CocoaPods not showing the latest version

**Comment by JoeSzymanski** [comment]
Bump again here. We could really use a new version pushed into the Cocoapods podspec repo.

**Comment by mcudich** [comment]
Done - apologies for the long delay!
